Azure-Samples/media-services-v3-python

CONTRIBUTING.md
* ...
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Updated the title on Contributing guide

README.md, VideoAnalytics/FaceRedactorEventBased/README.md
References to images and readme of the FaceRedactor sample were incorrect. They have been updates.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix: FaceRedactor sample references updated

README.md
* Typo "Git hub"→"GitHub"
https://github.com/Azure-Samples/media-services-v3-python/blob/main/README.md
#PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> Typo "Git hub"→"GitHub"

all/all-ams-python-sdk.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> iterative note

all/jobs.py, all/sample.env
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> jobs python

all/assets.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> hi, this is Sanjay!

all/assets.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Reverted back - Sanjay

all/transforms.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added transforms.py

all/assets.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> assets script

all/transforms.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Transforms

all/storage.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Storage snippets

Assets/get-container-from-asset.py, Assets/list-assets-filtered.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Asset files

Account/create-account-with-managed-identity.py, Account/create-account.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added Account files

Streaming/AssetFilters/asset-filters.py, Streaming/StreamFilesSample/stream-files-sample.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added Streaming files

AudioAnalytics/audio-analytics.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added AudioAnalytics file

VideoAnalytics/video-analytics.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added VideoAnalytics file

snippets/content-key-policies.py, snippets/filters.py, snippets/live-event.py, snippets/streaming-endpoints.py, snippets/streaming-locators.py, snippets/streaming-policies.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> More snippets

VideoEncoding/Encoding_Bulk_Remote_Storage_Account_SAS/encoding-bulk-remote-storage-account-sas.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> bulk remote sas sample

Common/encoding_job_helpers.py, VideoAnalytics/video-analytics-async-helper.py, VideoEncoding/CreateTransform_Job_PresetOverride/create-transform-job-preset-override-helper.py, VideoEncoding/EncodingLiveArchiveMP4/encoding-live-archive-to-mp4-helper.py, VideoEncoding/Encoding_AAC_AudioOnly/encoding-aac-audio-only-helper.py, VideoEncoding/Encoding_BuiltIn_CopyCodec/encoding-builtin-copycodec-helper.py, VideoEncoding/Encoding_BuiltIn_CopyCodecWithProxy/encoding-builtin-copycodecwithproxy-helper.py, VideoEncoding/Encoding_Custom_CopyCodec_Sprite+Proxy/encoding-custom-copycodec-sprite+proxy-helper.py, VideoEncoding/Encoding_H264 _with_EventHub/encoding-h264-with-eventhub-helper.py, VideoEncoding/Encoding_H264/encoding-h264-helper.py, VideoEncoding/Encoding_H264_ContentAware/encoding-h264-contentaware-helper.py, VideoEncoding/Encoding_H264_ContentAware_Constrained/encoding-h264-contentaware-constrained-helper.py, VideoEncoding/Encoding_H264_OverlayImage/encoding-h264-overlayimage-helper.py, VideoEncoding/Encoding_H264_Rotate90degrees/encoding-h264-rotate90degrees-helper.py, VideoEncoding/Encoding_H264_To_TransportStream/encoding-h264-to-transportstream-helper.py, VideoEncoding/Encoding_HEVC/encoding-hevc-helper.py, VideoEncoding/Encoding_HEVC_ContentAware/encoding-hevc-contentaware-helper.py, VideoEncoding/Encoding_HEVC_ContentAware_Constrained/encoding-hevc-contentaware-constrained-helper.py, VideoEncoding/Encoding_MultiChannel_Audio/encoding-multichannel-audio-helper.py, VideoEncoding/Encoding_Sprite_Thumbnail/encoding-sprite-thumbnail-helper.py, VideoEncoding/Encoding_Stitch_Two_Assets/encoding-stitch-two-assets-helper.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Helper function versions of code samples

VideoEncoding/CreateTransform_Job_PresetOverride/Readme.md, VideoEncoding/EncodingLiveArchiveMP4/Readme.md, VideoEncoding/Encoding_AAC_AudioOnly/Readme.md, VideoEncoding/Encoding_BuiltIn_CopyCodec/Readme.md, VideoEncoding/Encoding_BuiltIn_CopyCodecWithProxy/Readme.md, VideoEncoding/Encoding_H264 _with_EventHub/Readme.md, VideoEncoding/Encoding_H264/Readme.md, VideoEncoding/Encoding_H264_ContentAware/Readme.md, VideoEncoding/Encoding_H264_ContentAware_Constrained/Readme.md, VideoEncoding/Encoding_H264_OverlayImage/Readme.md, VideoEncoding/Encoding_H264_Rotate90degrees/Readme.md, VideoEncoding/Encoding_H264_To_TransportStream/Readme.md, VideoEncoding/Encoding_HEVC/Readme.md, VideoEncoding/Encoding_HEVC_ContentAware/Readme.md, VideoEncoding/Encoding_HEVC_ContentAware_Constrained/Readme.md, VideoEncoding/Encoding_Sprite_Thumbnail/Readme.md, VideoEncoding/Encoding_Stitch_Two_Assets/Readme.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Descriptions

cli/snippets, cli/snippets.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> cli snippets

VideoEncoding/EncodingLiveArchiveMP4/encoding-live-archive-to-mp4-helper.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Tags for inclusion
